### ISSUE TITLE
ice: panicked at 'span must have positive length'

### ISSUE THREAD

**Issue by thetayloredman** [zirco-lang/zrc#137]
### Before we begin...

- [X] I have updated the Zirco toolchain to the latest version
- [X] I have searched the issue tracker for duplicates

### What was the ICE diagnostic?

```
error: internal compiler error encountered: thread panicked
note: this is not your fault! this is ALWAYS a compiler bug.
note: compiler bugs threaten the Zirco ecosystem -- we would appreciate a bug report:
note: bug reporting link: https://github.com/zirco-lang/zrc/issues/new?template=ice.yml

note: zrc version 0.1.0 (36486080d6ae771151590c52e28582a4c4e9db2d, tainted!) built for x86_64-unknown-linux-gnu on 2023-12-03T14:22:40-08:00 (debug mode)
note: rustc 1.73.0 (cc66ad468 2023-10-03) (stable-x86_64-unknown-linux-gnu on linux-x86_64)
note: cargo 1.73.0 (9c4383fb5 2023-08-26)
note: tainted files:
note:   * Cargo.lock
note:   * compiler/zrc_diagnostics/Cargo.toml
note:   * compiler/zrc_diagnostics/src/lib.rs

note: command line arguments: target/debug/zrc -

thread 'main' panicked at compiler/zrc_utils/src/span.rs:33:9:
span must have positive length
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: zrc_utils::span::Span::from_positions
             at ./compiler/zrc_utils/src/span.rs:33:9
   3: zrc_diagnostics::display_source_window::{{closure}}
             at ./compiler/zrc_diagnostics/src/lib.rs:213:17
   4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:294:13
   5: core::iter::traits::iterator::Iterator::find::check::{{closure}}
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2926:20
   6: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold::enumerate::{{closure}}
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/enumerate.rs:86:27
   7: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2461:21
   8: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/enumerate.rs:92:9
   9: core::iter::traits::iterator::Iterator::find
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2930:9
  10: <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/filter.rs:59:9
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/map.rs:103:9
  12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/map.rs:103:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/spec_from_iter.rs:33:9
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/mod.rs:2696:9
  16: core::iter::traits::iterator::Iterator::collect
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2053:9
  17: zrc_diagnostics::display_source_window
             at ./compiler/zrc_diagnostics/src/lib.rs:207:17
  18: zrc_diagnostics::Diagnostic::print
             at ./compiler/zrc_diagnostics/src/lib.rs:277:13
  19: zrc::main
             at ./compiler/zrc/src/main.rs:328:44
  20: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: end internal compiler error. compilation failed.
```

### What were you doing when the panic occured?

`zrc -`

### Provide an example of code that causes the panic.

`fn f() {}`

**Comment by thetayloredman** [comment]
repr on HEAD (+ more descriptive error):

```
error: internal compiler error encountered: thread panicked
note: this is not your fault! this is ALWAYS a compiler bug.
note: compiler bugs threaten the Zirco ecosystem -- we would appreciate a bug report:
note: bug reporting link: https://github.com/zirco-lang/zrc/issues/new?template=ice.yml

note: zrc version 0.1.0 (d9181cabd76075fdbca82664dcd110e5083cdf87, not tainted) built for x86_64-unknown-linux-gnu on 2023-12-04T14:26:25-08:00 (debug mode)
note: rustc 1.73.0 (cc66ad468 2023-10-03) (stable-x86_64-unknown-linux-gnu on linux-x86_64)
note: cargo 1.73.0 (9c4383fb5 2023-08-26)

note: command line arguments: target/debug/zrc -

thread 'main' panicked at compiler/zrc_utils/src/span.rs:33:9:
span must have positive length (got span 8..7)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: zrc_utils::span::Span::from_positions
             at ./compiler/zrc_utils/src/span.rs:33:9
   3: zrc_diagnostics::display_source_window::{{closure}}
             at ./compiler/zrc_diagnostics/src/lib.rs:206:17
   4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:294:13
   5: core::iter::traits::iterator::Iterator::find::check::{{closure}}
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2926:20
   6: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold::enumerate::{{closure}}
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/enumerate.rs:86:27
   7: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2461:21
   8: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/enumerate.rs:92:9
   9: core::iter::traits::iterator::Iterator::find
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2930:9
  10: <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/filter.rs:59:9
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/map.rs:103:9
  12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/map.rs:103:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/spec_from_iter.rs:33:9
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/mod.rs:2696:9
  16: core::iter::traits::iterator::Iterator::collect
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2053:9
  17: zrc_diagnostics::display_source_window
             at ./compiler/zrc_diagnostics/src/lib.rs:200:17
  18: zrc_diagnostics::Diagnostic::print
             at ./compiler/zrc_diagnostics/src/lib.rs:270:13
  19: zrc::main
             at ./compiler/zrc/src/main.rs:328:44
  20: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: end internal compiler error. compilation failed.
```
