### ISSUE TITLE
bug: invalid llvm when assigning `void`

### ISSUE THREAD

**Issue by thetayloredman** [zirco-lang/zrc#40]
Is this possible?

```rs
fn x(); // void

let y = x();
// this might actually be valid code.
```

but consuming `void` is UB?
or is `void` valid to store but invalid to *use* (which i can't find a counterexample for?)

**Comment by thetayloredman** [comment]
Bug verified to cause invalid code generation.


```rs
fn void();
fn main() {
    let x = void();
    return;
}
```

Output LLVM:
```llvm
declare void @void()
define void @main() {
    %l1 = alloca void
    %l2 = alloca i8
    call void @void()
    store i8 undef, ptr %l2
    %l3 = load void, ptr %l2
    store void %l3, ptr %l1
    ret void
}
```

`llc` result:
```
llc: error: llc: i42.ll:3:18: error: void type only allowed for function results
    %l1 = alloca void
                 ^
```

**Comment by thetayloredman** [comment]
This bug exists in both the type checker and the code generator. It needs to be made so that `void` is code-generated as the `i8` except in function return position, or we need to prevent the need for the `undef` storing in the first place (allowing there to be no return value from expr_cg in some cases).

There needs to be a decision on if `let x = void();` would be valid in the above case (because it *should* be so that `void` is never _consumable_ and can *exist* as an `undef`? let's look into this more.)

**Known Workaround:** Do not assign anything to a `void` function call.
Severity: Moderate. Causes invalid CG, but workaround exists.

**Comment by thetayloredman** [comment]
Still confirmed in 7525a8fadb4d8faffd6c84e1869f1a42a8cdc274.

```llvm
declare void @f()
define void @main() {
    %l1 = alloca void
    call void () @f()
    store void undef, ptr %l1 ; << HERE
    ret void
}
```

**Comment by thetayloredman** [comment]
Needs repro on code generation v2.

**Comment by thetayloredman** [comment]
It shows now as:

```
error: internal compiler error encountered: thread panicked
note: this is not your fault! this is ALWAYS a compiler bug.
note: compiler bugs threaten the Zirco ecosystem -- we would appreciate a bug report:
note: bug reporting link: https://github.com/zirco-lang/zrc/issues/new?template=ice.yml

note: zrc version 0.1.0 (e458d600e0b68b670a2315f588592b7ec4084795, not tainted) built for x86_64-unknown-linux-gnu on 2023-11-08T11:47:57-08:00 (debug mode)
note: rustc 1.73.0 (cc66ad468 2023-10-03) (stable-x86_64-unknown-linux-gnu on linux-x86_64)
note: cargo 1.73.0 (9c4383fb5 2023-08-26)

note: command line arguments: target/debug/zrc -

thread 'main' panicked at compiler/zrc_codegen/src/ty.rs:89:23:
void is not a basic type
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: zrc_codegen::ty::llvm_basic_type
             at ./compiler/zrc_codegen/src/ty.rs:89:23
   3: zrc_codegen::stmt::cg_let_declaration
             at ./compiler/zrc_codegen/src/stmt.rs:62:17
   4: zrc_codegen::stmt::cg_block::{{closure}}
             at ./compiler/zrc_codegen/src/stmt.rs:262:66
   5: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2461:21
   6: zrc_codegen::stmt::cg_block
             at ./compiler/zrc_codegen/src/stmt.rs:119:5
   7: zrc_codegen::stmt::cg_program
             at ./compiler/zrc_codegen/src/stmt.rs:562:21
   8: zrc_codegen::stmt::cg_program_to_string
             at ./compiler/zrc_codegen/src/stmt.rs:633:35
   9: zrc::compile
             at ./compiler/zrc/src/main.rs:385:34
  10: zrc::main
             at ./compiler/zrc/src/main.rs:309:18
  11: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: end internal compiler error. compilation failed.
```
